language: node_js

node_js:
  - "node"

install:
  - "npm install"

script:
  - "npm run test:karma"
  - "npm run test:coverage"
  - "npm run lint"

before_install:
  - pip install --user codecov

after_success:
  - codecov
